ชื่อ: เปิดเซิร์ฟเวอร์มายคราฟ

เมื่อ:
  กำหนดเวลา:
    - cron: 0 0 * * *

งาน:
  เปิดเซิร์ฟเวอร์:
    รัน: ubuntu-latest
    ขั้นตอน:
      - ชื่อ: ติดตั้งมายคราฟ
        รัน: |
          sudo apt-get update
          sudo apt-get install -y default-jdk
          wget https://launcher.mojang.com/v1/objects/0a269b5f2c5b93b1712d0f5dc43b6182b9ab2548eff2d0f83e9e26e9257c/server.jar
          mv server.jar minecraft-server.jar

      - ชื่อ: เปิดเซิร์ฟเวอร์
        รัน: |
          java -Xmx1024M -Xms1024M -jar minecraft-server.jar nogui
